//! Protocol-service metadata and compatibility aliases.

pub static PROTOCOL_METHODS: &[(&str, &str, &str, bool, bool)] = &[
    (
        "system.hello",
        "Authenticate and negotiate a control protocol version.",
        "system.connect",
        false,
        false,
    ),
    (
        "system.get_capabilities",
        "List capabilities granted by this Odon build.",
        "system.introspect",
        false,
        false,
    ),
    (
        "system.list_methods",
        "List control methods and request schemas.",
        "system.introspect",
        false,
        false,
    ),
    (
        "system.describe_methods",
        "List control methods and request schemas.",
        "system.introspect",
        false,
        false,
    ),
    (
        "system.describe_events",
        "Describe initial event families and envelope fields.",
        "system.introspect",
        false,
        false,
    ),
    (
        "system.get_application_surface",
        "Get the feature-to-control parity manifest.",
        "system.introspect",
        false,
        false,
    ),
    (
        "ui.describe_schema",
        "Describe declarative UI schema v1 limits and vocabulary.",
        "ui.read",
        false,
        false,
    ),
    (
        "system.batch",
        "Execute application commands in order.",
        "system.batch",
        true,
        false,
    ),
    (
        "system.get_diagnostics",
        "Inspect bounded control-server state.",
        "system.introspect",
        false,
        false,
    ),
    (
        "events.subscribe",
        "Subscribe to server-pushed event patterns.",
        "events.read",
        false,
        false,
    ),
    (
        "events.unsubscribe",
        "Remove event subscriptions.",
        "events.read",
        false,
        false,
    ),
    (
        "events.get_status",
        "Inspect event queue diagnostics.",
        "events.read",
        false,
        false,
    ),
    (
        "tasks.start",
        "Run an application command as a retained task.",
        "tasks.write",
        true,
        true,
    ),
    (
        "tasks.get",
        "Get a task snapshot.",
        "tasks.read",
        false,
        false,
    ),
    (
        "tasks.list",
        "List retained tasks.",
        "tasks.read",
        false,
        false,
    ),
    (
        "tasks.cancel",
        "Cancel a queued task.",
        "tasks.write",
        true,
        false,
    ),
    (
        "tasks.forget",
        "Forget a terminal task.",
        "tasks.write",
        true,
        false,
    ),
    (
        "data.resources.register",
        "Register referenced external data.",
        "data.write",
        true,
        false,
    ),
    (
        "data.resources.list",
        "List registered external data.",
        "data.read",
        false,
        false,
    ),
    (
        "data.resources.get",
        "Get an external data descriptor.",
        "data.read",
        false,
        false,
    ),
    (
        "data.resources.remove",
        "Remove an unreferenced data descriptor.",
        "data.write",
        true,
        false,
    ),
    (
        "viewer.layers.add",
        "Add a referenced viewer layer.",
        "viewer.layers.write",
        true,
        false,
    ),
    (
        "viewer.layers.list",
        "List referenced viewer layers.",
        "viewer.layers.read",
        false,
        false,
    ),
    (
        "viewer.layers.get",
        "Get a referenced viewer layer.",
        "viewer.layers.read",
        false,
        false,
    ),
    (
        "viewer.layers.update",
        "Update layer state or style.",
        "viewer.layers.write",
        true,
        false,
    ),
    (
        "viewer.layers.remove",
        "Remove a referenced layer.",
        "viewer.layers.write",
        true,
        false,
    ),
    (
        "viewer.layers.reorder",
        "Set referenced layer order.",
        "viewer.layers.write",
        true,
        false,
    ),
    (
        "ui.extensions.register",
        "Register a declarative UI extension.",
        "ui.panels",
        true,
        false,
    ),
    (
        "ui.extensions.list",
        "List UI extensions.",
        "ui.read",
        false,
        false,
    ),
    (
        "ui.extensions.remove",
        "Remove an owned UI extension.",
        "ui.panels",
        true,
        false,
    ),
    (
        "ui.contributions.register",
        "Register a validated component tree.",
        "ui.panels",
        true,
        false,
    ),
    (
        "ui.contributions.list",
        "List component trees.",
        "ui.read",
        false,
        false,
    ),
    (
        "ui.contributions.patch_values",
        "Atomically patch retained UI values.",
        "ui.panels",
        true,
        false,
    ),
    (
        "ui.contributions.remove",
        "Remove an owned component tree.",
        "ui.panels",
        true,
        false,
    ),
];

pub static METHOD_ALIASES: &[(&str, &str)] = &[
    ("get_current_view", "app.get_state"),
    ("viewer.get_state", "app.get_state"),
    ("get_loading_state", "app.get_loading_state"),
    ("show_project_page", "app.navigation.show_project"),
    ("app.show_project_page", "app.navigation.show_project"),
    ("list_project_rois", "project.rois.list"),
    ("project.get_state", "project.rois.list"),
    ("open_project", "project.open"),
    ("save_project", "project.save"),
    ("open_roi", "project.rois.open"),
    ("open_ome_zarr", "datasets.open_ome_zarr"),
    ("open_tiff", "datasets.open_tiff"),
    (
        "open_mosaic_samplesheet",
        "datasets.open_mosaic_samplesheet",
    ),
    ("list_channels", "viewer.channels.list"),
    ("list_visible_channels", "viewer.channels.list_visible"),
    ("get_active_channel", "viewer.channels.get_active"),
    ("set_active_channel", "viewer.channels.set_active"),
    ("set_visible_channels", "viewer.channels.set_visible"),
    ("get_channel_contrast", "viewer.channels.get_contrast"),
    ("set_channel_contrast", "viewer.channels.set_contrast"),
    ("set_channel_order", "viewer.channels.set_order"),
    ("list_channel_groups", "viewer.channels.list_groups"),
    ("set_channel_group", "viewer.channels.set_group"),
    ("get_side_panels", "viewer.panels.get"),
    ("set_side_panels", "viewer.panels.set"),
    ("get_smooth_pixels", "viewer.rendering.get_smooth_pixels"),
    ("set_smooth_pixels", "viewer.rendering.set_smooth_pixels"),
    ("get_camera", "viewer.camera.get"),
    ("set_camera", "viewer.camera.set"),
    ("fit_to_view", "viewer.camera.fit"),
    ("zoom_in", "viewer.camera.zoom_in"),
    ("zoom_out", "viewer.camera.zoom_out"),
    (
        "get_object_overlay_visibility",
        "viewer.objects.get_visibility",
    ),
    (
        "set_object_overlay_visibility",
        "viewer.objects.set_visibility",
    ),
    ("get_object_selection", "viewer.objects.get_selection"),
    ("query_object_ids_in_rect", "viewer.objects.query_rect"),
    ("query_object_ids_in_view", "viewer.objects.query_view"),
    ("select_object_ids_in_rect", "viewer.objects.select_rect"),
    ("clear_object_selection", "viewer.objects.clear_selection"),
    ("get_object_filter", "viewer.objects.get_filter"),
    ("set_object_filter_query", "viewer.objects.set_filter"),
    ("clear_object_filter", "viewer.objects.clear_filter"),
    (
        "get_channel_intensity_stats",
        "viewer.channels.intensity_stats",
    ),
    ("set_right_tab", "viewer.ui.set_right_tab"),
    ("set_mosaic_right_tab", "mosaic.ui.set_right_tab"),
    ("configure_mosaic_layout", "mosaic.layout.configure"),
    ("capture_screenshot", "viewer.screenshot.capture"),
    ("capture_window_screenshot", "app.screenshot.capture"),
    ("capture_project_screenshot", "project.screenshot.capture"),
];
